baseurl = "https://kunlei.github.io"
title = "O.R. in Action"
languageCode = "en-us"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsOptions = "linenos=inline"
DefaultContentLanguage = "en"
disqusShortname = "orinaction"
googleAnalytics = "UA-124241468-1"

[permalinks]
  post = "/:year/:month/:day/:filename/"

[Params]
  subtitle = "Kunlei's Blog"
  logo = "img/myAvatar.png"
  favicon = "img/myAvatar.png"
  dateFormat = "January 2, 2006"
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[Author]
  name = "Kunlei Lian"
  email = "kunlei1987@gmail.com"
  # facebook = "realjenius"
  github = "kunlei"
  # twitter = "realjenius"
  linkedin = "kunlei-lian-ba55a73b"
  website = "https://kunlei.githu.io"

[[menu.main]]
  name = "Blog"
  url = "post"
  weight = 1

[[menu.main]]
  identifier = "coding"
  name = "Coding"
  weight = 3

[[menu.main]]
  parent = "coding"
  name = "Java"
  url = "/page/java-index"
  weight = 1

[[menu.main]]
  parent = "coding"
  name = "O.R."
  url = "/page/java-index"
  weight = 2



[[menu.main]]
  name = "About"
  url = "about"
  weight = 9

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 10