baseurl = "https://kunlei.github.io/"
title = "Operations Research in Action"
languageCode = "en-us"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsOptions = "linenos=inline"
DefaultContentLanguage = "en"
disqusShortname = "orinaction"
googleAnalytics = "UA-124241468-1"

[permalinks]
  post = "/:year/:month/:day/:filename/"

[Params]
  subtitle = "Kunlei's Personal Blog"
  logo = "img/myAvatar.png"
  favicon = "img/myAvatar.png"
  dateFormat = "January 2, 2006"
  rss = true
  comments = true

[Author]
  name = "Kunlei Lian"
  email = "kunlei1987@gmail.com"
  # facebook = "realjenius"
  github = "kunlei"
  # twitter = "realjenius"
  linkedin = "kunlei-lian-ba55a73b"

[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1

[[menu.main]]
  name = "About"
  url = "about"
  weight = 2

[[menu.main]]
    name = "Contact"
    url = "contact"
    weight = 3

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 4